### ISSUE TITLE
Geomap panel crashes on rerender

### ISSUE THREAD

**Issue by rdubrock** [grafana/scenes#102]
I'm not 100% sure this is a problem with scenes itself, but I think it might be

To reproduce:

- Add geomap panel to a scene with two tabs
- Click on a tab without the geomap panel
- Click back to the tab with the geomap panel

```
TypeError: can't access property "setActive", this.mouseWheelZoom is undefined
    initControls GeomapPanel.tsx:336
    optionsChanged GeomapPanel.tsx:161
    shouldComponentUpdate GeomapPanel.tsx:106
```    

![geomap_bug](https://user-images.githubusercontent.com/8377044/227284581-dcba58a1-6277-4aad-bd9e-a54156b8f2af.gif)

**Comment by dprokop** [comment]
@rdubrock thanks for reporting this. I have managed to reproduce this easily. 

I think I know where the problem is. It can be perceived either a scenes problem or geomap problem.

---

So what happens when you change tabs back and forth is that we are re-using scenes that are cached. When navigating back to the scene that once has been activated, we are only activating it back and initializing the options that are later on passed down to the particular panel. This happens here: https://github.com/grafana/scenes/blob/main/packages/scenes/src/components/VizPanel/VizPanel.tsx#L86. 

Please note, that the options object is a result of the underlying `lodash.merge` call, which will create a new **options object**.

Now, what happens down the road. In the Geomap panel, there is a `shouldComponentUpdate` called that simply compares current props.options and next props.options for referential equality (https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/geomap/GeomapPanel.tsx#L108) and initializes map controls accordingly. 

The open question we need to discuss tho is if panels should rely on referential equality - and the framework should guarantee that, or rather perform a legitimate deep comparison of the options.
