### ISSUE TITLE
SceneByFrameRepeater() does not work in Grafana 10.x

### ISSUE THREAD

**Issue by ptrkkr** [grafana/scenes#367]
Hi!

I have tried a lot to let `SceneByFrameRepeater()` work. Sometimes it did work with very bad performance (loading endless long) and now it does not work at all.
I am currently using the Grafana nightly build but have also tried many other versions starting from `10.0.0-preview`.
With `9.5.10` it works as it should. 
Am I missing something? 

The Grafana Scenes Demo app seems to use `9.5.0-105543pre` (https://github.com/grafana/scenes/blob/main/packages/scenes-app/docker-compose.yaml). I think it would be beneficial if the demo scenes app would use at least `10.1.x`. 

Thx!

**Comment by torkelo** [comment]
> Sometimes it did work with very bad performance (loading endless long) 

This is not caused by SceneByFrame repeater, it's super fast, at least when I am testing it it can handle repeating and rendering 100 graphs in milliseconds

@ptrkkr what data source are you using and what does the query result look like? Is there a data frame per series? 

We are not seeing any issues with it, tried it a few days ago and it works as it should. What are you seeing?

**Comment by dprokop** [comment]
Actually just run the docker image and it seems like the time series panel is not visible in the repeater demo. Stat however renders as intended. Looking into this now.

**Comment by torkelo** [comment]
@dprokop well it's not related to the repeater, it's related to the `  .setOption('legend', { displayMode: LegendDisplayMode.Hidden })`  on the TimeSeriesPanel 

The migration for that is not kicking in (because of how set pluginVersion I think). 

Fixes if you change to `.setOption('legend', { showLegend: false })`

**Comment by dprokop** [comment]
> The migration for that is not kicking in (because of how set pluginVersion I think).

@torkelo you are right. The migration does not kick in because it's handled via DashboardMigrator :/

**Comment by dprokop** [comment]
@ptrkkr Was the above helpful in solving the problem?

**Comment by ptrkkr** [comment]
Yes, thank you @dprokop! Now it's working perfectly fine
